---
title: "Run RMap Stats"
output: html_document
params:
  basedir:
    value: x
---

```{r, include=FALSE, eval=TRUE}
library(reticulate)
library(rstan)
library(loo)
library(tibble)
library(lme4)
library(lmerTest)
library(rstanarm)
options(MC.cores=parallel::detectCores())
```

```{python, include=FALSE, eval=TRUE}
import os, pickle
import pandas as pd
import numpy as np
import seaborn as sns
```

```{r}
#basedir = params$basedir
#basedir = paste(basedir,"/",sep="")
basedir = '/Users/jonathannicholas/gradschool/manuscripts/ataxia-rl/'
outdir = sprintf("%scode/fit_models/rm/summarized/",basedir)
```

# Run Stats on Behavior
---

## Load dataframes needed for stats

```{python}
ccas = pd.read_csv("%sdata/ccasRmScored.csv"%r.basedir)
rmdata = pd.read_csv("%sdata/rm/rmData4Stats.csv"%r.basedir)
ccas = ccas.merge(rmdata.groupby(["subject_id","patient_factor","group_coded"]).size().reset_index(name="count"),on=["subject_id"]).drop("count",axis=1)
ccas["ds_bwd"] = ccas["8_digitspan_bwd"]
ccas["ds_fwd"] = ccas["1_digitspan_fwd"]
ccas["sem"] = ccas["2_semantic_fluency"]
ccas["phon"] = ccas["3_phonemic_fluency"]
ccas["cat"] = ccas["4_category_switching"]
ccas["verb"] = ccas["9_verbal_recall"]
ccas["sim"] = ccas["5_similarity"]
ccas["gng"] = ccas["6_gonogo"]

rmdata = rmdata.merge(ccas[["subject_id","ds_bwd","ds_fwd","sem","phon","cat","verb","sim","gng"]],on=["subject_id"])
```

## LM for neuropsych scores
```{r}
dsbwd_m = stan_lmer(ds_bwd ~ group_coded + (group_coded | patient_factor), data = py$ccas)
dsbwd_table = data.frame(summary(dsbwd_m, probs=c(0.975,0.025,0.9,0.1),digits=3))

dsfwd_m = stan_lmer(ds_fwd ~ group_coded + (group_coded | patient_factor), data = py$ccas)
dsfwd_table = data.frame(summary(dsfwd_m, probs=c(0.975,0.025,0.9,0.1),digits=3))

sem_m = stan_lmer(sem ~ group_coded + (group_coded | patient_factor), data = py$ccas)
sem_table = data.frame(summary(sem_m, probs=c(0.975,0.025,0.9,0.1),digits=3))

phon_m = stan_lmer(phon ~ group_coded + (group_coded | patient_factor), data = py$ccas)
phon_table = data.frame(summary(phon_m, probs=c(0.975,0.025,0.9,0.1),digits=3))

cat_m = stan_lmer(cat ~ group_coded + (group_coded | patient_factor), data = py$ccas)
cat_table = data.frame(summary(cat_m, probs=c(0.975,0.025,0.9,0.1),digits=3))

verb_m = stan_lmer(verb ~ group_coded + (group_coded | patient_factor), data = py$ccas)
verb_table = data.frame(summary(verb_m, probs=c(0.975,0.025,0.9,0.1),digits=3))

sim_m = stan_lmer(sim ~ group_coded + (group_coded | patient_factor), data = py$ccas)
sim_table = data.frame(summary(sim_m, probs=c(0.975,0.025,0.9,0.1),digits=3))

gng_m = stan_lmer(gng ~ group_coded + (group_coded | patient_factor), data = py$ccas)
gng_table = data.frame(summary(gng_m, probs=c(0.975,0.025,0.9,0.1),digits=3))

```

```{python}
dsfwd_table = r.dsfwd_table
dsfwd_table["effect"] = dsfwd_table.index
dsfwd_table.to_csv(os.path.join(r.outdir,"dsfwd_stat_effects.csv"))
dsbwd_table = r.dsbwd_table
dsbwd_table["effect"] = dsbwd_table.index
dsbwd_table.to_csv(os.path.join(r.outdir,"dsbwd_stat_effects.csv"))
sem_table = r.sem_table
sem_table["effect"] = sem_table.index
sem_table.to_csv(os.path.join(r.outdir,"sem_stat_effects.csv"))
phon_table = r.phon_table
phon_table["effect"] = phon_table.index
phon_table.to_csv(os.path.join(r.outdir,"phon_stat_effects.csv"))
cat_table = r.cat_table
cat_table["effect"] = cat_table.index
cat_table.to_csv(os.path.join(r.outdir,"cat_stat_effects.csv"))
verb_table = r.verb_table
verb_table["effect"] = verb_table.index
verb_table.to_csv(os.path.join(r.outdir,"verb_stat_effects.csv"))
sim_table = r.sim_table
sim_table["effect"] = sim_table.index
sim_table.to_csv(os.path.join(r.outdir,"sim_stat_effects.csv"))
gng_table = r.gng_table
gng_table["effect"] = gng_table.index
gng_table.to_csv(os.path.join(r.outdir,"gng_stat_effects.csv"))
```

# LM for grp effects/sensitivity to task difficulty on accuracy
```{r}
py$rmdata["ds_bwd"] = as.vector(scale(py$rmdata$ds_bwd))
py$rmdata["rt"] = as.vector(scale(py$rmdata$rt))
acc_m = stan_glmer(accuracy ~ group_coded*pFReward1 + group_coded*I(pFReward1^2) + ds_bwd + rt + (group_coded*pFReward1 + group_coded*I(pFReward1^2) | patient_factor), data = py$rmdata, family = binomial, cores=4)
acc_table = data.frame(summary(acc_m, probs=c(0.975,0.025,0.9,0.1),digits=3))
```

```{python}
acc_table = r.acc_table
acc_table["effect"] = acc_table.index
acc_table.to_csv(os.path.join(r.outdir,"acc_stat_effects.csv"))
```

# LM for grp effects on reaction time
```{python}
rtdata = pd.read_csv("%sdata/rm/rtData4Stats.csv"%r.basedir)
```

```{r}
rt_m = stan_glmer(rt ~ group_coded + (group_coded | ctrl_patient_id), data = py$rtdata, cores=4)
rt_table = data.frame(summary(rt_m, probs=c(0.975,0.025,0.9,0.1),digits=3))
```

```{python}
rt_table = r.rt_table
rt_table["effect"] = rt_table.index
rt_table.to_csv(os.path.join(r.outdir,"rt_stat_effects.csv"))
```

# LM for grp effects on model fit
```{python}
elpds = pd.read_csv("%scode/fit_models/rm/summarized/rm_elpd_diffs.csv"%r.basedir)
ccas2 = ccas
ccas2["subject_id"] = ccas2.subject_id.str.zfill(3)
elpds = elpds.merge(ccas[["subject_id","ds_bwd","ds_fwd"]],on=["subject_id"])
```

```{r}
py$elpds["ds_bwd"] = as.vector(scale(py$elpds$ds_bwd))
elpd_m = stan_glmer(elpd_diff ~ group_coded + ds_bwd + (group_coded | patient_factor), data = py$elpds, cores=4)
elpd_table = data.frame(summary(elpd_m, probs=c(0.975,0.025,0.9,0.1),digits=3))
```

```{python}
elpd_table = r.elpd_table
elpd_table["effect"] = elpd_table.index
elpd_table.to_csv(os.path.join(r.outdir,"elpd_stat_effects.csv"))
```

